Repository bpm-crafters/process-engine-api, pull requests merged in 2024-10, with the labels that each got.

#90 Implement UserTaskSupport component
  engine-adapter/adapter-commons/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/commons/task/AbstractTaskSubscriptionApiImpl.kt
  engine-adapter/adapter-commons/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/commons/task/CompositeTaskHandler.kt
  engine-adapter/adapter-commons/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/commons/task/CompositeTaskTerminationHandler.kt
  engine-adapter/adapter-commons/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/commons/task/InMemSubscriptionRepository.kt
  engine-adapter/adapter-commons/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/commons/task/RefreshableDelivery.kt
  engine-adapter/adapter-commons/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/commons/task/SubscriptionRepository.kt
  engine-adapter/adapter-commons/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/commons/task/TaskSubscriptionHandle.kt
  engine-adapter/adapter-commons/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/commons/task/UserTaskSupport.kt
  engine-adapter/adapter-commons/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/commons/task/VariablesExt.kt
  engine-adapter/adapter-commons/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/commons/task/UserTaskSupportTest.kt
  engine-adapter/camunda-platform-8-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/task/delivery/SubscribingRefreshingUserTaskDelivery.kt
Labels: Prio: MUST, Type: enhancement, Status: in progress

#102 Add jgiven support
  engine-adapter/adapter-testing/pom.xml
  engine-adapter/camunda-platform-7-embedded-core/pom.xml
  engine-adapter/camunda-platform-7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/testing/AbstractC7EmbeddedStage.kt
  engine-adapter/camunda-platform-8-core/pom.xml
  engine-adapter/camunda-platform-8-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/testing/AbstractC8ProcessStage.kt
Labels: Prio: MUST, Type: enhancement, Status: in progress

#109 104 create example jgiven bdd tests
  engine-adapter/camunda-platform-7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/testing/AbstractC7EmbeddedStage.kt
  engine-adapter/camunda-platform-8-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/correlation/CorrelationApiImpl.kt
  engine-adapter/camunda-platform-8-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/testing/AbstractC8ProcessStage.kt
  examples/java-c7-remote/src/main/resources/simple-process.bpmn
  examples/java-c7/pom.xml
  examples/java-c7/src/main/resources/simple-process.bpmn
  examples/java-c7/src/test/java/dev/bpmcrafters/example/common/adapter/out/process/SimpleProcessStages.java
  examples/java-c7/src/test/java/dev/bpmcrafters/example/common/adapter/out/process/SimpleProcessTest.java
  examples/java-c7/src/test/resources/camunda.cfg.xml
  examples/java-c8/pom.xml
  examples/java-c8/src/main/java/dev/bpmcrafters/example/javac8/JavaCamunda8ExampleApplication.java
  examples/java-c8/src/main/resources/simple-process.bpmn
  examples/java-c8/src/test/java/.gitkeep
  examples/java-c8/src/test/java/dev/bpmcrafters/example/common/adapter/out/process/SimpleProcessStages.java
  examples/java-c8/src/test/java/dev/bpmcrafters/example/common/adapter/out/process/SimpleProcessTest.java
  examples/java-common-fixture/pom.xml
  examples/java-common-fixture/src/main/java/dev/bpmcrafters/example/common/adapter/TaskHandlerConfiguration.java
  examples/java-common-fixture/src/main/java/dev/bpmcrafters/example/common/adapter/in/process/ExecuteActionTaskHandler.java
  examples/java-common-fixture/src/main/java/dev/bpmcrafters/example/common/adapter/out/process/InMemUserTaskAdapter.java
  examples/java-common-fixture/src/main/java/dev/bpmcrafters/example/common/adapter/out/process/UserTaskAdapter.java
  examples/java-common-fixture/src/main/java/dev/bpmcrafters/example/common/adapter/out/process/WorkflowAdapter.java
  examples/java-common-fixture/src/main/java/dev/bpmcrafters/example/common/adapter/shared/SimpleProcessWorkflowConst.java
  examples/java-common-fixture/src/main/java/dev/bpmcrafters/example/common/application/port/out/UserTaskOutPort.java
  examples/java-common-fixture/src/main/java/dev/bpmcrafters/example/common/application/port/out/WorkflowOutPort.java
  examples/java-common-fixture/src/main/java/dev/bpmcrafters/example/common/application/usecase/CorrelateUseCase.java
  examples/java-common-fixture/src/main/java/dev/bpmcrafters/example/common/application/usecase/DeployUseCase.java
  examples/java-common-fixture/src/main/java/dev/bpmcrafters/example/common/application/usecase/PerformUserTaskUseCase.java
  examples/java-common-fixture/src/main/java/dev/bpmcrafters/example/common/application/usecase/SignalUseCase.java
  examples/java-common-fixture/src/main/java/dev/bpmcrafters/example/common/application/usecase/StartProcessInstanceUseCase.java
Labels: Prio: SHOULD, Type: enhancement, Status: in progress

#110 Implementation for C7 event and pull delivery
  engine-adapter/camunda-platform-7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/task/delivery/event/EmbeddedEventBasedUserTaskDelivery.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/C7EmbeddedAdapterAutoConfiguration.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/C7EmbeddedAdapterConditions.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/C7EmbeddedAdapterProperties.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/event/C7EmbeddedEmbeddedEventBasedUserTaskUserTaskDeliveryBinding.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/event/C7EmbeddedEventDeliveryAutoConfiguration.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/initial/C7EmbeddedInitialPullOnStartupAutoConfiguration.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/job/C7EmbeddedJobDeliveryAutoConfiguration.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/schedule/C7EmbeddedSchedulingAutoConfiguration.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/schedule/C7EmbeddedServiceTaskPullStrategyAutoConfiguration.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/schedule/C7EmbeddedUserTaskPullStrategyAutoConfiguration.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  engine-adapter/camunda-platform-7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/task/delivery/TaskInformationExtensions.kt
  engine-adapter/camunda-platform-8-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/task/delivery/TaskInformationExtensions.kt
  examples/java-c7/simple-process-demo.http
  examples/java-c7/src/main/resources/application.yml
  examples/java-c7/src/main/resources/simple-process.bpmn
  examples/java-c8/docker-compose-local.yaml
  examples/java-c8/src/main/resources/application-c8-run.yml
Labels: Prio: MUST, Type: enhancement, Status: in progress

#111 Add spring tests for c7
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/pom.xml
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/C7EmbeddedAdapterProperties.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/event/C7EmbeddedEmbeddedEventBasedUserTaskUserTaskDeliveryBinding.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/schedule/C7EmbeddedSchedulingAutoConfiguration.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/AbstractC7EmbeddedSpringApiITest.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/C7EmbeddedSpringAdapterConditionTest.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/C7EmbeddedSpringProcessTestHelper.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/C7EmbeddedSpringStartProcessApiITest.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/C7EmbeddedSpringTaskApiITest.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/C7EmbeddedTestApplication.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/test/resources/application-itest.yml
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/test/resources/banner.txt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/test/resources/bpmn/simple-process.bpmn
Labels: Prio: MUST, Status: in progress
