Repository bpm-crafters/process-engine-api, pull requests merged in 2025-02, with the labels that each got.

#172 chore: Klogging migrated to io.github.oshai:kotlin-logging-jvm
  engine-adapter/adapter-commons/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/commons/task/AbstractTaskSubscriptionApiImpl.kt
  engine-adapter/adapter-commons/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/commons/task/UserTaskSupport.kt
  engine-adapter/adapter-testing/src/main/kotlin/dev/bpmcrafters/processengineapi/test/BaseGivenWhenStage.kt
  engine-adapter/adapter-testing/src/main/kotlin/dev/bpmcrafters/processengineapi/test/BaseThenStage.kt
  engine-adapter/camunda-platform-7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/correlation/CorrelationApiImpl.kt
  engine-adapter/camunda-platform-7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/correlation/SignalApiImpl.kt
  engine-adapter/camunda-platform-7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/deploy/DeploymentApiImpl.kt
  engine-adapter/camunda-platform-7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/process/StartProcessApiImpl.kt
  engine-adapter/camunda-platform-7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/task/completion/C7ServiceTaskCompletionApiImpl.kt
  engine-adapter/camunda-platform-7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/task/completion/C7UserTaskCompletionApiImpl.kt
  engine-adapter/camunda-platform-7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/task/delivery/event/EmbeddedEventBasedUserTaskDelivery.kt
  engine-adapter/camunda-platform-7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/task/delivery/job/EmbeddedTaskDeliveryEnginePlugin.kt
  engine-adapter/camunda-platform-7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/task/delivery/job/EmbeddedTaskDeliveryJobHandler.kt
  engine-adapter/camunda-platform-7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/task/delivery/job/JobCreatingExternalServiceTaskListener.kt
  engine-adapter/camunda-platform-7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/task/delivery/job/JobCreatingUserTaskListener.kt
  engine-adapter/camunda-platform-7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/task/delivery/pull/EmbeddedPullServiceTaskDelivery.kt
  engine-adapter/camunda-platform-7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/task/delivery/pull/EmbeddedPullUserTaskDelivery.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/C7EmbeddedAdapterAutoConfiguration.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/event/C7EmbeddedEventDeliveryAutoConfiguration.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/initial/C7EmbeddedInitialPullOnStartupAutoConfiguration.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/initial/C7EmbeddedInitialPullServiceTasksDeliveryBinding.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/initial/C7EmbeddedInitialPullUserTasksDeliveryBinding.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/schedule/C7EmbeddedSchedulingAutoConfiguration.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/schedule/C7EmbeddedServiceTaskPullStrategyAutoConfiguration.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/schedule/C7EmbeddedUserTaskPullStrategyAutoConfiguration.kt
  engine-adapter/camunda-platform-7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/correlation/CorrelationApiImpl.kt
  engine-adapter/camunda-platform-7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/correlation/SignalApiImpl.kt
  engine-adapter/camunda-platform-7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/deploy/DeploymentApiImpl.kt
  engine-adapter/camunda-platform-7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/process/StartProcessApiImpl.kt
  engine-adapter/camunda-platform-7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/task/completion/C7RemoteClientServiceTaskCompletionApiImpl.kt
  engine-adapter/camunda-platform-7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/task/completion/C7RemoteServiceServiceTaskCompletionApiImpl.kt
  engine-adapter/camunda-platform-7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/task/completion/C7RemoteServiceUserTaskCompletionApiImpl.kt
  engine-adapter/camunda-platform-7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/task/delivery/pull/RemotePullServiceTaskDelivery.kt
  engine-adapter/camunda-platform-7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/task/delivery/pull/RemotePullUserTaskDelivery.kt
  engine-adapter/camunda-platform-7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/task/delivery/subscribe/SubscribingClientServiceTaskDelivery.kt
  engine-adapter/camunda-platform-8-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/correlation/CorrelationApiImpl.kt
  engine-adapter/camunda-platform-8-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/correlation/SignalApiImpl.kt
  engine-adapter/camunda-platform-8-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/deploy/DeploymentApiImpl.kt
  engine-adapter/camunda-platform-8-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/process/StartProcessApiImpl.kt
  engine-adapter/camunda-platform-8-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/task/completion/C8TaskListClientUserTaskCompletionApiImpl.kt
  engine-adapter/camunda-platform-8-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/task/completion/C8ZeebeExternalServiceTaskCompletionApiImpl.kt
  engine-adapter/camunda-platform-8-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/task/completion/C8ZeebeUserTaskCompletionApiImpl.kt
  engine-adapter/camunda-platform-8-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/task/delivery/PullUserTaskDelivery.kt
  engine-adapter/camunda-platform-8-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/task/delivery/SubscribingRefreshingUserTaskDelivery.kt
  engine-adapter/camunda-platform-8-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/task/delivery/SubscribingServiceTaskDelivery.kt
  engine-adapter/camunda-platform-8-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/springboot/schedule/C8SchedulingAutoConfiguration.kt
  engine-adapter/camunda-platform-8-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/springboot/schedule/RefreshingUserTaskDeliveryBinding.kt
  engine-adapter/camunda-platform-8-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/springboot/schedule/ScheduledUserTaskDeliveryBinding.kt
  engine-adapter/camunda-platform-8-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/springboot/subscription/C8SubscriptionAutoConfiguration.kt
  engine-adapter/camunda-platform-8-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/springboot/subscription/SubscribingServiceTaskDeliveryBinding.kt
  engine-adapter/camunda-platform-8-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c8/springboot/subscription/SubscribingUserTaskDeliveryBinding.kt
  examples/java-common-fixture/pom.xml
  examples/java-common-fixture/src/main/java/dev/bpmcrafters/example/common/CommonFixtureAutoconfiguration.java
  pom.xml
Labels: Prio: MUST

#183 fix: update klogging
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/pom.xml
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/C7RemoteAdapterAutoConfiguration.kt
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/client/C7RemoteClientServiceTaskAutoConfiguration.kt
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/initial/C7RemoteInitialPullOnStartupAutoConfiguration.kt
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/initial/C7RemoteInitialPullServiceTasksDeliveryBinding.kt
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/initial/C7RemoteInitialPullUserTasksDeliveryBinding.kt
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/schedule/C7RemoteSchedulingAutoConfiguration.kt
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/schedule/C7RemoteServiceTaskPullStrategyAutoConfiguration.kt
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/schedule/C7RemoteUserTaskPullStrategyAutoConfiguration.kt
  examples/java-c7-remote/pom.xml
  examples/java-c7/pom.xml
Labels: Type: bug

#187 Fix strategy remote_subscribed
  engine-adapter/adapter-testing/src/main/kotlin/dev/bpmcrafters/processengineapi/test/BaseGivenWhenStage.kt
  engine-adapter/camunda-platform-7-remote-core/pom.xml
  engine-adapter/camunda-platform-7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/task/delivery/pull/RemotePullServiceTaskDelivery.kt
  engine-adapter/camunda-platform-7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/task/delivery/pull/RemotePullUserTaskDelivery.kt
  engine-adapter/camunda-platform-7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/task/delivery/subscribe/SubscribingClientServiceTaskDelivery.kt
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/pom.xml
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/client/C7RemoteClientServiceTaskAutoConfiguration.kt
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/AbstractC7RemoteApiITestBase.kt
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/C7RemoteProcessTestHelper.kt
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/C7RemoteStartProcessApiITest.kt
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/C7RemoteTaskApiITest.kt
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/C7RemoteTaskApiSubscribedITest.kt
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/C7RemoteTestApplication.kt
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/test/resources/application-itest-subscribed.yml
Labels: Prio: MUST, Type: bug

#196 Get rid of `process-engine-api-adapter-commons-spring-boot-starter` module
  engine-adapter/adapter-commons-spring-boot-starter/pom.xml
  engine-adapter/adapter-commons-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/commons/spring/AbstractQualifiedBeanCondition.kt
  engine-adapter/adapter-commons-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/commons/spring/ConditionalOnMissingQualifiedBean.kt
  engine-adapter/adapter-commons-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/commons/spring/OnMissingQualifiedBeanCondition.kt
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/pom.xml
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/springboot/C7EmbeddedAdapterAutoConfiguration.kt
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/pom.xml
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/C7RemoteAdapterAutoConfiguration.kt
  engine-adapter/camunda-platform-8-spring-boot-starter/pom.xml
  pom.xml
Labels: Prio: MUST, Type: enhancement

#198 Use spring-boot-conditions under new maven coordinates
  engine-adapter/camunda-platform-7-embedded-spring-boot-starter/pom.xml
  engine-adapter/camunda-platform-7-remote-spring-boot-starter/pom.xml
  pom.xml
Labels: Prio: MUST
